dae/urls.py
# -*- coding:utf:8 -*-
__author__ = 'chenzwcc'

from dae import views
from django.conf.urls import url

urlpatterns = [
    url(r'^decry/$',views.DecryptionViews.as_view(),name='decry'),  #解密

    url(r'^encry/$',views.EncryptionViews.as_view(),name='encry'),  #加密

    url(r'^download/(?P<file_name>[\w\W]*)/$',views.download,name='download')
]

des/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from des.settings import STATIC_ROOT,DAE_FILE_UPLOAD_DIR


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dae/',include('dae.urls',namespace='dae')),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': DAE_FILE_UPLOAD_DIR}),
    # 配置static,解决debug为false时static路径设置无效
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

]


# 全局404页面配置
handler404 = 'dae.views.page_not_found'
# 全局500页面配置
handler500 = 'dae.views.page_error'

dae/models.py
from django.db import models

# Create your models here.

dae/views.py
from django.shortcuts import render,render_to_response,HttpResponse
from django.views.generic.base import View
from django import conf
from django.http import FileResponse

import os,time,json
import xlwt,xlrd
from xlutils.copy import copy

from dae import oper_excel
from dae import gener_excel


class DecryptionViews(View):
    """解密"""
    def get(self,request):

        return render(request,'jiemi.html')

    def post(self,request):
        field_str = request.POST.get('text')
        field_list = field_str.split('!')
        field_from_html = []
        for i in field_list:
            if len(i) != 0:
                upload_dir = os.path.join(conf.settings.DAE_FILE_UPLOAD_DIR, str(int(time.time())))
                if not os.path.isdir(upload_dir):
                    os.makedirs(upload_dir)
                file_obj = request.FILES.get('file')
                file_name = os.path.join(upload_dir, file_obj.name)
                with open(file_name, 'wb') as f:
                    for chunks in file_obj.chunks():
                        f.write(chunks)
                if i in oper_excel.getFields(oper_excel.getSheets(file_name)[0]):
                    field_from_html.append(i)
                else:
                    return render(request, 'jiemi.html', {'err_msg': "填写的字段有误"})
        field_dict = {}
        field_from_excel = oper_excel.getFields(oper_excel.getSheets(file_name)[0])
        for i in field_from_html:
            if i in field_from_excel:
                key = oper_excel.one_field_to_Decrydata(file_name,i ,'123456789')
                field_dict[i]=key
        dealed_file=gener_excel.Decrypt_data_to_excel(file_name,field_dict)
        return render(request,'jiemi.html',{'field_str':field_str,'file_name':dealed_file})





class EncryptionViews(View):
    """加密"""
    def get(self,request):
        return render(request, 'jiami.html')

    def post(self, request):
        field_str = request.POST.get('text')
        field_list = field_str.split('!')
        field_from_html = []
        for i in field_list:
            if len(i) != 0:
                upload_dir = os.path.join(conf.settings.DAE_FILE_UPLOAD_DIR, str(int(time.time())))
                if not os.path.isdir(upload_dir):
                    os.makedirs(upload_dir)
                file_obj = request.FILES.get('file')
                file_name = os.path.join(upload_dir, file_obj.name)
                with open(file_name, 'wb') as f:
                    for chunks in file_obj.chunks():
                        f.write(chunks)
                if i in oper_excel.getFields(oper_excel.getSheets(file_name)[0]):
                    field_from_html.append(i)
                else:
                    return render(request, 'jiami.html', {'err_msg': "填写的字段或分隔符有误"})
        field_dict = {}
        field_from_excel = oper_excel.getFields(oper_excel.getSheets(file_name)[0])
        for i in field_from_html:
            if i in field_from_excel:
                key = oper_excel.one_field_to_Encrydata(file_name, i, '123456789')
                field_dict[i] = key
        dealed_file = gener_excel.Encrypted_data_to_excel(file_name, field_dict)

        return render(request, 'jiami.html', dict(field_str=field_str, file_name=dealed_file))

def download(request,file_name):
    file = open(file_name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/vnd.ms-excel'
    path, file = os.path.split(file_name)

    response['Content-Disposition'] = 'attachment;filename="%s"'%file

    return response



# 404
def page_not_found(request):
    response = render_to_response('404.html', {})
    response.status_code = 404
    return response


# 500
def page_error(request):
    response = render_to_response('500.html', {})
    response.status_code = 500
    return response

"""处理上传的文件"""
# @csrf_exempt
# def FileUpload(request):
#     if not request.FILES.get('file').name.endswith('.xlsx'):
#         return HttpResponse(json.dumps({"status":False,'err_msg':'The file format must be excel' }))
#     else:
#         upload_dir = os.path.join(conf.settings.DAE_FILE_UPLOAD_DIR,str(int(time.time())))
#         if not os.path.isdir(upload_dir):
#             os.makedirs(upload_dir)
#
#         file_obj=request.FILES.get('file')
#         print(file_obj,type(file_obj))
#         if len(os.listdir(upload_dir))<2:
#             with open(os.path.join(upload_dir,file_obj.name),'wb') as f:
#                 for chunks in file_obj.chunks():
#                     f.write(chunks)
#         else:
#             return HttpResponse(json.dumps({"status":False,'err_msg':'max upload limit is 2' }))
#         return HttpResponse(json.dumps({'status':True}))
#     # f=open(os.path.join('fileupload',file_obj.name),'wb')
#     # for line in file_obj.chunks():
#     #     f.write(line)
#     # table=os.getcwd()+r'\fileupload\\'+file_obj.name
#     # table_list = oper_excel.getSheets(table)
#     # field_list = oper_excel.getFields(table_list[0])
#     # print(field_list)
#     #
#     # return render(request,'jiemi.html',{'len':len(field_list),"field_list":field_list})

templates/jiami.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DES加解密系统</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/dashboard.css"/>

</head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dae:encry' %}">DES加解密系统</a>
        </div>

      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="{% url 'dae:encry' %}">加密<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'dae:decry' %}">解密</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <form action="{% url 'dae:encry' %}" method="post" enctype="multipart/form-data">
                <h3 class="sub-header">请添加需要加密的Excel文件</h3>
               <div class="form-group">

                    <input type="file" id="exampleInputFile" name="file"/>
                    <span id="helpBlock2" class="help-block"></span>
                </div>
                {% if err_msg %}
                <p style="color: red">{{ err_msg }}</p>
                {% endif %}
                    <h3 class="sub-header">请添加需要操作的字段并以'!'分割</h3>
                    <div class="form-group">

                        <input type="text" class="form-control" name="text" id="exampleInputText" placeholder="例如 name!age" value="{{ field_str }}">
                    </div>
                    <button id="fileSubmit" type="submit" class="btn btn-success">Submit</button>
                {% csrf_token %}
            </form>
            {% if file_name %}
            <h3 class="sub-header">加密后的文件</h3>
		  <div class="table-responsive">
			  <table class="table table-striped">
			    <tbody>
		          <tr>

		                <a href="{% url 'dae:download' file_name %}">{{ file_name }}</a>

		          </tr>

		        </tbody>
			  </table>
		  </div>
         {% endif %}
        </div>

        </div>
      </div>



    <script src="/static/js/jquery.min.js"></script>
    <script>

    $("#fileSubmit").click(function() {
         var oFile=$("#exampleInputFile");
         var oFileText=$("#exampleInputText");
         var oFileMessage=$("#helpBlock2");

         if((oFileText.val().indexOf("!")>=1&&oFile.val().indexOf(".xlsx")>=0)||(oFileText.val().indexOf("!")>=1&&oFile.val().indexOf(".xls")>=0)){

         }else{
            alert("因格式错误导致验证失败,请重新输入！");
            return false;
         }
    });
    </script>


    </body>
</html>

templates/jiemi.html
<!DOCTYPE html>
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DES加解密系统</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/dashboard.css"/>


  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'dae:decry' %}">DES加解密系统</a>
        </div>

      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'dae:encry' %}">加密<span class="sr-only">(current)</span></a></li>
            <li class="active"><a href="{% url 'dae:decry' %}">解密</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <form action="{% url 'dae:decry' %}" method="post" enctype="multipart/form-data">
                <h3 class="sub-header">请添加需要解密的Excel文件</h3>
               <div class="form-group">

                    <input type="file" id="exampleInputFile" name="file"/>
                    <span id="helpBlock2" class="help-block"></span>
                </div>
                {% if err_msg %}
                <p style="color: red">{{ err_msg }}</p>
                {% endif %}
                    <h3 class="sub-header">请添加需要操作的字段并以'!'分割</h3>
                    <div class="form-group">

                        <input type="text" class="form-control" name="text" id="exampleInputText" placeholder="例如 name!age" value="{{ field_str }}">
                    </div>
                    <button id="fileSubmit" type="submit" class="btn btn-success">Submit</button>
                {% csrf_token %}
            </form>
		{% if file_name %}
            <h3 class="sub-header">解密后的文件</h3>
		  <div class="table-responsive">
			  <table class="table table-striped">
			    <tbody>
		          <tr>

		                <a href="{% url 'dae:download' file_name %}">{{ file_name }}</a>

		          </tr>

		        </tbody>
			  </table>
		  </div>
         {% endif %}


        </div>
      </div>
    </div>


    <script src="/static/js/jquery.min.js"></script>
    <script>

    $("#fileSubmit").click(function() {
         var oFile=$("#exampleInputFile");
         var oFileText=$("#exampleInputText");
         var oFileMessage=$("#helpBlock2");

         if((oFileText.val().indexOf("!")>=1&&oFile.val().indexOf(".xlsx")>=0)||(oFileText.val().indexOf("!")>=1&&oFile.val().indexOf(".xls")>=0)){

         }else{
            alert("因格式错误导致验证失败,请重新输入！");
            return false;
         }
    });
    </script>


    </body>
</html>